services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    PhpSolution\SwaggerUIGen\Bundle\Service\DataProviderFactory: ~

    PhpSolution\SwaggerUIGen\Component\DataProvider\DataProviderInterface:
        class: 'PhpSolution\SwaggerUIGen\Component\DataProvider\YamlDataProvider'
        arguments: [[], [], []]
        factory: ['@PhpSolution\SwaggerUIGen\Bundle\Service\DataProviderFactory', 'createDataProvider']

    PhpSolution\SwaggerUIGen\Component\SwaggerProvider:
        class: 'PhpSolution\SwaggerUIGen\Component\SwaggerProvider'
        arguments: [~]