openapi: 3.0.0
servers:
    - url: http://localhost

info:
    description: ""
    version: "1.0"
    title: ""

externalDocs:
    description: "Find out more about Swagger"
    url: "http://swagger.io"